### ISSUE TITLE
MIGRATION_STATEMENT_TIMEOUT=0 and multiple migration

### ISSUE THREAD

**Issue by ombr** [ankane/slowpoke#12]
I have on my environment MIGRATION_STATEMENT_TIMEOUT=0 so my migration do not get a timeout.

But it seems I can not pass two migrations at the same time with this environement variable set.

Here is the error I get:

`PG::ConnectionBad: connection is closed: ROLLBACK`

Any ideas ?

Thanks.

**Comment by ankane** [comment]
Hey @ombr, thanks for reporting. Fixed on master.

**Comment by ombr** [comment]
@ankane Just updated and it worked :smile: ! Do you know when you will release a new version with the patch ?
