### ISSUE TITLE
Release 0.2.1?

### ISSUE THREAD

**Issue by cllns** [ankane/slowpoke#14]
We had trouble with Slowpoke on our CI server. I see this is fixed on master (https://github.com/ankane/slowpoke/commit/9c0c67799d09ddbfbcf4147f6c38ffbf44a6b378) but not in a released gem.

When you get a chance @ankane, could you release 0.2.1?

Thanks!

**Comment by ankane** [comment]
Hey @cllns, you can point your Gemfile to the master branch.

**Comment by cllns** [comment]
I'm aware, thanks. Just figured others could run into this same problem.
