### ISSUE TITLE
Subscribing to timeout notification but still fetching the exception

### ISSUE THREAD

**Issue by courtsimas** [ankane/slowpoke#21]
I realize that ActiveSupport's Notifications are just meant to instrument and subscribe to events, but since you're swallowing Rack Timeout's RequestTimeoutException, I am not sure how to grab the exception from a timeout and pass it to new relic. Previously, with Rack Timeout I could do this:

```
    rescue_from Rack::Timeout::RequestTimeoutException do |exception|
      Rails.logger.debug exception.message
      Rails.logger.debug exception.backtrace[0..20].join("\n")
      NewRelic::Agent.notice_error exception, custom_params: custom_new_relic_params
      # ...
      another_custom_method(exception)
    end
```

But now, with slowpoke, since the subscribing to the event doesn't give me the exception, what would you recommend? Since we're using this all api based and not using the customer 503 page, is there anyway to turn off your rescuing of the `Rack::Timeout::RequestTimeoutException` so that I can catch it myself?

This is what we've got so far:

```
    ActiveSupport::Notifications.subscribe "timeout.slowpoke" do |name, start, finish, id, payload|
      Rails.logger.debug name
      Rails.logger.debug payload
      # ... 
    end
```

**Comment by ankane** [comment]
Hey @courtsimas, Slowpoke doesn't touch `Rack::Timeout::RequestTimeoutException` (that's all internal to rack-timeout), so not sure what you're seeing is related to Slowpoke.

**Comment by courtsimas** [comment]
You rescue it and serve a service_unavailable status (for the 503 page). That’s unique to slowpoke. 

I ended up forking it and just commenting out your rescues that serve that status so I can rescue the exception myself and that worked. If you’d like, I can submit a PR that turns that feature on or off with an env var...

**Comment by ankane** [comment]
Slowpoke rescues `Rack::Timeout::RequestTimeoutError`, not `Rack::Timeout::RequestTimeoutException`. Rails does the same for things like `ActiveRecord::RecordNotFound`. This shouldn't interfere with rescuing exceptions with `rescue_from` instead a controller.

**Comment by ankane** [comment]
Here's the difference between the errors: https://github.com/sharpstone/rack-timeout/blob/master/doc/exceptions.md

**Comment by ankane** [comment]
Cleaning up issues. For future readers, Slowpoke doesn't actually rescue anything - it just tells Rails to show a specific error page for specific exception types.
