### ISSUE TITLE
Use in conjunction with Rack::Timeout?

### ISSUE THREAD

**Issue by mrthankyou** [ankane/slowpoke#22]
It's not very clear from the documentation but does Slowpoke use Rack::Timeout baked in? I see that Rack::Timeout has various settings such as:

```
  service_timeout:   15,     # ENV["RACK_TIMEOUT_SERVICE_TIMEOUT"]
  wait_timeout:      30,     # ENV["RACK_TIMEOUT_WAIT_TIMEOUT"]
  wait_overtime:     60,     # ENV["RACK_TIMEOUT_WAIT_OVERTIME"]
  service_past_wait: false,  # ENV["RACK_TIMEOUT_SERVICE_PAST_WAIT"]
  term_on_timeout:   false   # ENV["RACK_TIMEOUT_TERM_ON_TIMEOUT"]
```

but I don't know if Slowpoke also catches these. From briefly reviewing your code it doesn't look like that's the case. Any guidance or best practice advice is much appreciated. Thank you.

**Comment by ankane** [comment]
Slowpoke adds functionality on top of Rack::Timeout, so all the Rack::Timeout environment variables should work (`config.slowpoke.timeout` will override the `service_timeout` if it's set).

**Comment by mrthankyou** [comment]
Thanks for the quick response!

So if I understand right, there is no need for me to add `Rack::Timeout` to my application since slowpoke adds that functionality automatically?

**Comment by ankane** [comment]
Yeah, Slowpoke will add it

**Comment by mrthankyou** [comment]
Thanks! That answers my question. Closing the ticket.

**Comment by ibrahima** [comment]
I realize this is an old issue, but I had a related question and wanted to confirm - if we want to set one of the other configuration parameters for Rack::Timeout, we should use the environment variables right? It doesn't seem like slowpoke passes along any other parameters to Rack::Timeout.

Here's where I could find it inserting the Rack::Timeout middleware
https://github.com/ankane/slowpoke/blob/d98700964dd1648acc59915f76e88cc871bae38a/lib/slowpoke/railtie.rb#L20

or if using dynamic timeouts:
https://github.com/ankane/slowpoke/blob/d98700964dd1648acc59915f76e88cc871bae38a/lib/slowpoke/timeout.rb#L12

Thanks!
