### ISSUE TITLE
Slowpoke on Puma

### ISSUE THREAD

**Issue by gillesbergerp** [ankane/slowpoke#23]
We recently tried introducing request timeouts for our Rails application using the Rack::Timeout gem which resulted in a couple of issues. After some more research, we discovered Slowpoke which seems to be more stable in our use case but whenever a request runs into the timeout, Puma doesn't seem to be killed correctly. We see a log "Gracefully stopping, waiting for requests to finish" indicating that Puma is shutting down but the application is not terminated. 
How should we best handle this case?

Our setup is as follows:
* JRuby 9.3.4.0
* Rails 6.1.7.2
* Puma 6.2.1

Note: We run Puma with only one worker

Any help would be very much appreciated

**Comment by ankane** [comment]
Hi @gillesbergerp, unfortunately, I don't have the bandwidth to help with app-specific issues, but a few things you could try:

1. Add debugging to see where the code is timing out (it may be stuck in a C call)
2. Customize the [`on_timeout` behavior](https://github.com/ankane/slowpoke#safer-service-timeouts) to send a stronger termination signal (`SIGQUIT` or `SIGKILL`) after a certain amount of time
