### ISSUE TITLE
Restarting Passenger process

### ISSUE THREAD

**Issue by dush** [ankane/slowpoke#4]
Slowpoke is Unicorn specific when it comes to restarting application process.
To be able to cleanly restart aplication process managed by Passenger (5.0.x) I nedded to modify my initializer
````ruby
if defined?(::PhusionPassenger)
  Rack::Timeout.unregister_state_change_observer(:slowpoke)

  Rack::Timeout.register_state_change_observer(:passenger_killer) do |env|
    case env[Rack::Timeout::ENV_INFO_KEY].state
      when :timed_out       
        `passenger-config detach-process #{Process.pid}`
    end
  end
end
````

**Comment by ankane** [comment]
Thanks for reporting Pavel!  Fixed in the latest release with this commit. https://github.com/ankane/slowpoke/commit/7bc5e75432e41b5bb5ac7b74a41371b3aed373f2
