### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by NielsKSchjoedt** [ankane/slowpoke#8]
Hi

I'm trying to get slowpoke to work with my rails app.

in the documentation it says:

```
The default timeout is 15 seconds. Change this with:

Slowpoke.timeout = 10
```

But where do I set this? If I set it in application.rb it says that Slowpoke is not known, and the same happens in an initializer.

**Comment by ankane** [comment]
It should work in either place. What error are you seeing?
